name: "Publish docs"
on:
  push:
    branches:
      - main

env:
  CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_PAGES_API_TOKEN}}

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: Setup actions
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          registry-url: https://registry.npmjs.org
      - name: Create dist directory
        run: |
          mkdir dist
          cp {index.html,logo-border.svg,favicon.ico} dist/
      - name: Install wrangler
        run: npm i -g wrangler
      - name: Deploy
        run: wrangler pages deploy dist --project-name oslo --branch main
